// Embed the compiled physics module (build/physics.wasm) as base64 in
// src/graph/physicsWasmBinary.ts, so the worker can instantiate it without a
// fetch (works identically under Vite dev, the production bundle, and Tauri).
// Runs as part of `npm run asbuild`.
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const wasm = fs.readFileSync(path.join(root, "build", "physics.wasm"));
const b64 = wasm.toString("base64");

const out = `// AUTO-GENERATED by scripts/embed-wasm.cjs — do not edit.
// Source: assembly/physics.ts, compiled via \`npm run asbuild\`.
export const wasmBase64 =
  "${b64}";
`;

fs.writeFileSync(path.join(root, "src", "graph", "physicsWasmBinary.ts"), out);
console.log(`embedded physics.wasm (${wasm.length} bytes) → src/graph/physicsWasmBinary.ts`);
